# ============================================================================
# Test users — demo-only. Permanent passwords are generated by Terraform and
# exposed via the `test_user_passwords` sensitive output (see outputs.tf).
#
# FUTURE (SSO): Delete this entire file once Entra federation lands. Real
# users are provisioned on first login via SAML/OIDC, identified by their
# Entra OID rather than a hardcoded username. The Identity Pool mapping
# rules (identity-pool.tf) will switch from `username Equals <user>` to a
# group-claim rule.
# ============================================================================

resource "random_password" "test_user" {
  for_each = local.user_set

  length  = 20
  upper   = true
  lower   = true
  numeric = true
  special = true

  min_upper   = 2
  min_lower   = 2
  min_numeric = 2
  min_special = 1

  # Cognito's default password policy rejects some symbols in error messages
  # and URL-encoding is annoying for manual testing — constrain the set.
  override_special = "!@#$%^&*()-_=+"
}

resource "aws_cognito_user" "test" {
  for_each = local.user_set

  user_pool_id = local.user_pool_id
  username     = each.value

  attributes = {
    email          = "${each.value}@${local.hostname}"
    email_verified = "true"
  }

  password       = random_password.test_user[each.value].result
  message_action = "SUPPRESS"

  lifecycle {
    ignore_changes = [
      # Don't re-churn users just because a password rotation would be a no-op.
      password,
    ]
  }
}
